/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedKycRouteImport } from './routes/_authenticated/kyc'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCommissionStatementRouteImport } from './routes/_authenticated/commission-statement'
import { Route as AuthenticatedPromoterRouteRouteImport } from './routes/_authenticated/promoter/route'
import { Route as AuthenticatedCustomerRouteRouteImport } from './routes/_authenticated/customer/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedRewardCertificateRewardIdRouteImport } from './routes/_authenticated/reward-certificate.$rewardId'
import { Route as AuthenticatedReceiptsReceiptNumberRouteImport } from './routes/_authenticated/receipts.$receiptNumber'
import { Route as AuthenticatedPromoterRankRouteImport } from './routes/_authenticated/promoter/rank'
import { Route as AuthenticatedPromoterPortfolioRouteImport } from './routes/_authenticated/promoter/portfolio'
import { Route as AuthenticatedPromoterLuckyDrawRouteImport } from './routes/_authenticated/promoter/lucky-draw'
import { Route as AuthenticatedPromoterCustomersRouteImport } from './routes/_authenticated/promoter/customers'
import { Route as AuthenticatedPromoterCommissionsRouteImport } from './routes/_authenticated/promoter/commissions'
import { Route as AuthenticatedPromoterCollectionsRouteImport } from './routes/_authenticated/promoter/collections'
import { Route as AuthenticatedCustomerRewardsRouteImport } from './routes/_authenticated/customer/rewards'
import { Route as AuthenticatedCustomerReferralsRouteImport } from './routes/_authenticated/customer/referrals'
import { Route as AuthenticatedCustomerReceiptsRouteImport } from './routes/_authenticated/customer/receipts'
import { Route as AuthenticatedCustomerPaymentsRouteImport } from './routes/_authenticated/customer/payments'
import { Route as AuthenticatedCustomerMembershipRouteImport } from './routes/_authenticated/customer/membership'
import { Route as AuthenticatedCustomerLuckyDrawRouteImport } from './routes/_authenticated/customer/lucky-draw'
import { Route as AuthenticatedCustomerInstallmentsRouteImport } from './routes/_authenticated/customer/installments'
import { Route as AuthenticatedCustomerEnrollRouteImport } from './routes/_authenticated/customer/enroll'
import { Route as AuthenticatedCustomerDrawResultsRouteImport } from './routes/_authenticated/customer/draw-results'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminSiteSettingsRouteImport } from './routes/_authenticated/admin/site-settings'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminRewardsRouteImport } from './routes/_authenticated/admin/rewards'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin/reports'
import { Route as AuthenticatedAdminRemindersRouteImport } from './routes/_authenticated/admin/reminders'
import { Route as AuthenticatedAdminReminderTemplatesRouteImport } from './routes/_authenticated/admin/reminder-templates'
import { Route as AuthenticatedAdminReminderJobsRouteImport } from './routes/_authenticated/admin/reminder-jobs'
import { Route as AuthenticatedAdminReferralTreeRouteImport } from './routes/_authenticated/admin/referral-tree'
import { Route as AuthenticatedAdminReceiptsRouteImport } from './routes/_authenticated/admin/receipts'
import { Route as AuthenticatedAdminRanksRouteImport } from './routes/_authenticated/admin/ranks'
import { Route as AuthenticatedAdminPromotersRouteImport } from './routes/_authenticated/admin/promoters'
import { Route as AuthenticatedAdminPlansRouteImport } from './routes/_authenticated/admin/plans'
import { Route as AuthenticatedAdminPlanDeletionsRouteImport } from './routes/_authenticated/admin/plan-deletions'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin/payments'
import { Route as AuthenticatedAdminMembershipsRouteImport } from './routes/_authenticated/admin/memberships'
import { Route as AuthenticatedAdminMembershipEmailsRouteImport } from './routes/_authenticated/admin/membership-emails'
import { Route as AuthenticatedAdminLuckyDrawRouteImport } from './routes/_authenticated/admin/lucky-draw'
import { Route as AuthenticatedAdminKycEmailsRouteImport } from './routes/_authenticated/admin/kyc-emails'
import { Route as AuthenticatedAdminIncentivesRouteImport } from './routes/_authenticated/admin/incentives'
import { Route as AuthenticatedAdminGiftsRouteImport } from './routes/_authenticated/admin/gifts'
import { Route as AuthenticatedAdminExportsRouteImport } from './routes/_authenticated/admin/exports'
import { Route as AuthenticatedAdminEmailPreviewRouteImport } from './routes/_authenticated/admin/email-preview'
import { Route as AuthenticatedAdminDrawResultsRouteImport } from './routes/_authenticated/admin/draw-results'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated/admin/customers'
import { Route as AuthenticatedAdminCommissionsRouteImport } from './routes/_authenticated/admin/commissions'
import { Route as AuthenticatedAdminAuditLogRouteImport } from './routes/_authenticated/admin/audit-log'
import { Route as AuthenticatedAdminApprovalsRouteImport } from './routes/_authenticated/admin/approvals'
import { Route as AuthenticatedAdminSplatRouteImport } from './routes/_authenticated/admin/$'
import { Route as ApiPublicRazorpayWebhookRouteImport } from './routes/api/public/razorpay/webhook'
import { Route as ApiPublicHooksReconcilePaymentsRouteImport } from './routes/api/public/hooks/reconcile-payments'
import { Route as ApiPublicHooksProcessPaymentRemindersRouteImport } from './routes/api/public/hooks/process-payment-reminders'
import { Route as ApiPublicHooksProcessExportJobsRouteImport } from './routes/api/public/hooks/process-export-jobs'
import { Route as ApiPublicHooksEnqueuePaymentRemindersRouteImport } from './routes/api/public/hooks/enqueue-payment-reminders'
import { Route as AuthenticatedAdminViewAsUserIdRouteImport } from './routes/_authenticated/admin/view-as.$userId'
import { Route as ApiAdminDrawsDrawIdPickRouteImport } from './routes/api/admin/draws.$drawId.pick'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKycRoute = AuthenticatedKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommissionStatementRoute =
  AuthenticatedCommissionStatementRouteImport.update({
    id: '/commission-statement',
    path: '/commission-statement',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPromoterRouteRoute =
  AuthenticatedPromoterRouteRouteImport.update({
    id: '/promoter',
    path: '/promoter',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomerRouteRoute =
  AuthenticatedCustomerRouteRouteImport.update({
    id: '/customer',
    path: '/customer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedRewardCertificateRewardIdRoute =
  AuthenticatedRewardCertificateRewardIdRouteImport.update({
    id: '/reward-certificate/$rewardId',
    path: '/reward-certificate/$rewardId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReceiptsReceiptNumberRoute =
  AuthenticatedReceiptsReceiptNumberRouteImport.update({
    id: '/receipts/$receiptNumber',
    path: '/receipts/$receiptNumber',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPromoterRankRoute =
  AuthenticatedPromoterRankRouteImport.update({
    id: '/rank',
    path: '/rank',
    getParentRoute: () => AuthenticatedPromoterRouteRoute,
  } as any)
const AuthenticatedPromoterPortfolioRoute =
  AuthenticatedPromoterPortfolioRouteImport.update({
    id: '/portfolio',
    path: '/portfolio',
    getParentRoute: () => AuthenticatedPromoterRouteRoute,
  } as any)
const AuthenticatedPromoterLuckyDrawRoute =
  AuthenticatedPromoterLuckyDrawRouteImport.update({
    id: '/lucky-draw',
    path: '/lucky-draw',
    getParentRoute: () => AuthenticatedPromoterRouteRoute,
  } as any)
const AuthenticatedPromoterCustomersRoute =
  AuthenticatedPromoterCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedPromoterRouteRoute,
  } as any)
const AuthenticatedPromoterCommissionsRoute =
  AuthenticatedPromoterCommissionsRouteImport.update({
    id: '/commissions',
    path: '/commissions',
    getParentRoute: () => AuthenticatedPromoterRouteRoute,
  } as any)
const AuthenticatedPromoterCollectionsRoute =
  AuthenticatedPromoterCollectionsRouteImport.update({
    id: '/collections',
    path: '/collections',
    getParentRoute: () => AuthenticatedPromoterRouteRoute,
  } as any)
const AuthenticatedCustomerRewardsRoute =
  AuthenticatedCustomerRewardsRouteImport.update({
    id: '/rewards',
    path: '/rewards',
    getParentRoute: () => AuthenticatedCustomerRouteRoute,
  } as any)
const AuthenticatedCustomerReferralsRoute =
  AuthenticatedCustomerReferralsRouteImport.update({
    id: '/referrals',
    path: '/referrals',
    getParentRoute: () => AuthenticatedCustomerRouteRoute,
  } as any)
const AuthenticatedCustomerReceiptsRoute =
  AuthenticatedCustomerReceiptsRouteImport.update({
    id: '/receipts',
    path: '/receipts',
    getParentRoute: () => AuthenticatedCustomerRouteRoute,
  } as any)
const AuthenticatedCustomerPaymentsRoute =
  AuthenticatedCustomerPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedCustomerRouteRoute,
  } as any)
const AuthenticatedCustomerMembershipRoute =
  AuthenticatedCustomerMembershipRouteImport.update({
    id: '/membership',
    path: '/membership',
    getParentRoute: () => AuthenticatedCustomerRouteRoute,
  } as any)
const AuthenticatedCustomerLuckyDrawRoute =
  AuthenticatedCustomerLuckyDrawRouteImport.update({
    id: '/lucky-draw',
    path: '/lucky-draw',
    getParentRoute: () => AuthenticatedCustomerRouteRoute,
  } as any)
const AuthenticatedCustomerInstallmentsRoute =
  AuthenticatedCustomerInstallmentsRouteImport.update({
    id: '/installments',
    path: '/installments',
    getParentRoute: () => AuthenticatedCustomerRouteRoute,
  } as any)
const AuthenticatedCustomerEnrollRoute =
  AuthenticatedCustomerEnrollRouteImport.update({
    id: '/enroll',
    path: '/enroll',
    getParentRoute: () => AuthenticatedCustomerRouteRoute,
  } as any)
const AuthenticatedCustomerDrawResultsRoute =
  AuthenticatedCustomerDrawResultsRouteImport.update({
    id: '/draw-results',
    path: '/draw-results',
    getParentRoute: () => AuthenticatedCustomerRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminSiteSettingsRoute =
  AuthenticatedAdminSiteSettingsRouteImport.update({
    id: '/site-settings',
    path: '/site-settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRewardsRoute =
  AuthenticatedAdminRewardsRouteImport.update({
    id: '/rewards',
    path: '/rewards',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRemindersRoute =
  AuthenticatedAdminRemindersRouteImport.update({
    id: '/reminders',
    path: '/reminders',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminReminderTemplatesRoute =
  AuthenticatedAdminReminderTemplatesRouteImport.update({
    id: '/reminder-templates',
    path: '/reminder-templates',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminReminderJobsRoute =
  AuthenticatedAdminReminderJobsRouteImport.update({
    id: '/reminder-jobs',
    path: '/reminder-jobs',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminReferralTreeRoute =
  AuthenticatedAdminReferralTreeRouteImport.update({
    id: '/referral-tree',
    path: '/referral-tree',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminReceiptsRoute =
  AuthenticatedAdminReceiptsRouteImport.update({
    id: '/receipts',
    path: '/receipts',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRanksRoute = AuthenticatedAdminRanksRouteImport.update({
  id: '/ranks',
  path: '/ranks',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminPromotersRoute =
  AuthenticatedAdminPromotersRouteImport.update({
    id: '/promoters',
    path: '/promoters',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPlansRoute = AuthenticatedAdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminPlanDeletionsRoute =
  AuthenticatedAdminPlanDeletionsRouteImport.update({
    id: '/plan-deletions',
    path: '/plan-deletions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMembershipsRoute =
  AuthenticatedAdminMembershipsRouteImport.update({
    id: '/memberships',
    path: '/memberships',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMembershipEmailsRoute =
  AuthenticatedAdminMembershipEmailsRouteImport.update({
    id: '/membership-emails',
    path: '/membership-emails',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLuckyDrawRoute =
  AuthenticatedAdminLuckyDrawRouteImport.update({
    id: '/lucky-draw',
    path: '/lucky-draw',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminKycEmailsRoute =
  AuthenticatedAdminKycEmailsRouteImport.update({
    id: '/kyc-emails',
    path: '/kyc-emails',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminIncentivesRoute =
  AuthenticatedAdminIncentivesRouteImport.update({
    id: '/incentives',
    path: '/incentives',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminGiftsRoute = AuthenticatedAdminGiftsRouteImport.update({
  id: '/gifts',
  path: '/gifts',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminExportsRoute =
  AuthenticatedAdminExportsRouteImport.update({
    id: '/exports',
    path: '/exports',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEmailPreviewRoute =
  AuthenticatedAdminEmailPreviewRouteImport.update({
    id: '/email-preview',
    path: '/email-preview',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDrawResultsRoute =
  AuthenticatedAdminDrawResultsRouteImport.update({
    id: '/draw-results',
    path: '/draw-results',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCustomersRoute =
  AuthenticatedAdminCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCommissionsRoute =
  AuthenticatedAdminCommissionsRouteImport.update({
    id: '/commissions',
    path: '/commissions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAuditLogRoute =
  AuthenticatedAdminAuditLogRouteImport.update({
    id: '/audit-log',
    path: '/audit-log',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminApprovalsRoute =
  AuthenticatedAdminApprovalsRouteImport.update({
    id: '/approvals',
    path: '/approvals',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSplatRoute = AuthenticatedAdminSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const ApiPublicRazorpayWebhookRoute =
  ApiPublicRazorpayWebhookRouteImport.update({
    id: '/api/public/razorpay/webhook',
    path: '/api/public/razorpay/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksReconcilePaymentsRoute =
  ApiPublicHooksReconcilePaymentsRouteImport.update({
    id: '/api/public/hooks/reconcile-payments',
    path: '/api/public/hooks/reconcile-payments',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProcessPaymentRemindersRoute =
  ApiPublicHooksProcessPaymentRemindersRouteImport.update({
    id: '/api/public/hooks/process-payment-reminders',
    path: '/api/public/hooks/process-payment-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProcessExportJobsRoute =
  ApiPublicHooksProcessExportJobsRouteImport.update({
    id: '/api/public/hooks/process-export-jobs',
    path: '/api/public/hooks/process-export-jobs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksEnqueuePaymentRemindersRoute =
  ApiPublicHooksEnqueuePaymentRemindersRouteImport.update({
    id: '/api/public/hooks/enqueue-payment-reminders',
    path: '/api/public/hooks/enqueue-payment-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminViewAsUserIdRoute =
  AuthenticatedAdminViewAsUserIdRouteImport.update({
    id: '/view-as/$userId',
    path: '/view-as/$userId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const ApiAdminDrawsDrawIdPickRoute = ApiAdminDrawsDrawIdPickRouteImport.update({
  id: '/api/admin/draws/$drawId/pick',
  path: '/api/admin/draws/$drawId/pick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/customer': typeof AuthenticatedCustomerRouteRouteWithChildren
  '/promoter': typeof AuthenticatedPromoterRouteRouteWithChildren
  '/commission-statement': typeof AuthenticatedCommissionStatementRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/kyc': typeof AuthenticatedKycRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/$': typeof AuthenticatedAdminSplatRoute
  '/admin/approvals': typeof AuthenticatedAdminApprovalsRoute
  '/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/admin/commissions': typeof AuthenticatedAdminCommissionsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/draw-results': typeof AuthenticatedAdminDrawResultsRoute
  '/admin/email-preview': typeof AuthenticatedAdminEmailPreviewRoute
  '/admin/exports': typeof AuthenticatedAdminExportsRoute
  '/admin/gifts': typeof AuthenticatedAdminGiftsRoute
  '/admin/incentives': typeof AuthenticatedAdminIncentivesRoute
  '/admin/kyc-emails': typeof AuthenticatedAdminKycEmailsRoute
  '/admin/lucky-draw': typeof AuthenticatedAdminLuckyDrawRoute
  '/admin/membership-emails': typeof AuthenticatedAdminMembershipEmailsRoute
  '/admin/memberships': typeof AuthenticatedAdminMembershipsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/plan-deletions': typeof AuthenticatedAdminPlanDeletionsRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/admin/promoters': typeof AuthenticatedAdminPromotersRoute
  '/admin/ranks': typeof AuthenticatedAdminRanksRoute
  '/admin/receipts': typeof AuthenticatedAdminReceiptsRoute
  '/admin/referral-tree': typeof AuthenticatedAdminReferralTreeRoute
  '/admin/reminder-jobs': typeof AuthenticatedAdminReminderJobsRoute
  '/admin/reminder-templates': typeof AuthenticatedAdminReminderTemplatesRoute
  '/admin/reminders': typeof AuthenticatedAdminRemindersRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/rewards': typeof AuthenticatedAdminRewardsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/site-settings': typeof AuthenticatedAdminSiteSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/customer/draw-results': typeof AuthenticatedCustomerDrawResultsRoute
  '/customer/enroll': typeof AuthenticatedCustomerEnrollRoute
  '/customer/installments': typeof AuthenticatedCustomerInstallmentsRoute
  '/customer/lucky-draw': typeof AuthenticatedCustomerLuckyDrawRoute
  '/customer/membership': typeof AuthenticatedCustomerMembershipRoute
  '/customer/payments': typeof AuthenticatedCustomerPaymentsRoute
  '/customer/receipts': typeof AuthenticatedCustomerReceiptsRoute
  '/customer/referrals': typeof AuthenticatedCustomerReferralsRoute
  '/customer/rewards': typeof AuthenticatedCustomerRewardsRoute
  '/promoter/collections': typeof AuthenticatedPromoterCollectionsRoute
  '/promoter/commissions': typeof AuthenticatedPromoterCommissionsRoute
  '/promoter/customers': typeof AuthenticatedPromoterCustomersRoute
  '/promoter/lucky-draw': typeof AuthenticatedPromoterLuckyDrawRoute
  '/promoter/portfolio': typeof AuthenticatedPromoterPortfolioRoute
  '/promoter/rank': typeof AuthenticatedPromoterRankRoute
  '/receipts/$receiptNumber': typeof AuthenticatedReceiptsReceiptNumberRoute
  '/reward-certificate/$rewardId': typeof AuthenticatedRewardCertificateRewardIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/view-as/$userId': typeof AuthenticatedAdminViewAsUserIdRoute
  '/api/public/hooks/enqueue-payment-reminders': typeof ApiPublicHooksEnqueuePaymentRemindersRoute
  '/api/public/hooks/process-export-jobs': typeof ApiPublicHooksProcessExportJobsRoute
  '/api/public/hooks/process-payment-reminders': typeof ApiPublicHooksProcessPaymentRemindersRoute
  '/api/public/hooks/reconcile-payments': typeof ApiPublicHooksReconcilePaymentsRoute
  '/api/public/razorpay/webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/admin/draws/$drawId/pick': typeof ApiAdminDrawsDrawIdPickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/customer': typeof AuthenticatedCustomerRouteRouteWithChildren
  '/promoter': typeof AuthenticatedPromoterRouteRouteWithChildren
  '/commission-statement': typeof AuthenticatedCommissionStatementRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/kyc': typeof AuthenticatedKycRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/$': typeof AuthenticatedAdminSplatRoute
  '/admin/approvals': typeof AuthenticatedAdminApprovalsRoute
  '/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/admin/commissions': typeof AuthenticatedAdminCommissionsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/draw-results': typeof AuthenticatedAdminDrawResultsRoute
  '/admin/email-preview': typeof AuthenticatedAdminEmailPreviewRoute
  '/admin/exports': typeof AuthenticatedAdminExportsRoute
  '/admin/gifts': typeof AuthenticatedAdminGiftsRoute
  '/admin/incentives': typeof AuthenticatedAdminIncentivesRoute
  '/admin/kyc-emails': typeof AuthenticatedAdminKycEmailsRoute
  '/admin/lucky-draw': typeof AuthenticatedAdminLuckyDrawRoute
  '/admin/membership-emails': typeof AuthenticatedAdminMembershipEmailsRoute
  '/admin/memberships': typeof AuthenticatedAdminMembershipsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/plan-deletions': typeof AuthenticatedAdminPlanDeletionsRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/admin/promoters': typeof AuthenticatedAdminPromotersRoute
  '/admin/ranks': typeof AuthenticatedAdminRanksRoute
  '/admin/receipts': typeof AuthenticatedAdminReceiptsRoute
  '/admin/referral-tree': typeof AuthenticatedAdminReferralTreeRoute
  '/admin/reminder-jobs': typeof AuthenticatedAdminReminderJobsRoute
  '/admin/reminder-templates': typeof AuthenticatedAdminReminderTemplatesRoute
  '/admin/reminders': typeof AuthenticatedAdminRemindersRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/rewards': typeof AuthenticatedAdminRewardsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/site-settings': typeof AuthenticatedAdminSiteSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/customer/draw-results': typeof AuthenticatedCustomerDrawResultsRoute
  '/customer/enroll': typeof AuthenticatedCustomerEnrollRoute
  '/customer/installments': typeof AuthenticatedCustomerInstallmentsRoute
  '/customer/lucky-draw': typeof AuthenticatedCustomerLuckyDrawRoute
  '/customer/membership': typeof AuthenticatedCustomerMembershipRoute
  '/customer/payments': typeof AuthenticatedCustomerPaymentsRoute
  '/customer/receipts': typeof AuthenticatedCustomerReceiptsRoute
  '/customer/referrals': typeof AuthenticatedCustomerReferralsRoute
  '/customer/rewards': typeof AuthenticatedCustomerRewardsRoute
  '/promoter/collections': typeof AuthenticatedPromoterCollectionsRoute
  '/promoter/commissions': typeof AuthenticatedPromoterCommissionsRoute
  '/promoter/customers': typeof AuthenticatedPromoterCustomersRoute
  '/promoter/lucky-draw': typeof AuthenticatedPromoterLuckyDrawRoute
  '/promoter/portfolio': typeof AuthenticatedPromoterPortfolioRoute
  '/promoter/rank': typeof AuthenticatedPromoterRankRoute
  '/receipts/$receiptNumber': typeof AuthenticatedReceiptsReceiptNumberRoute
  '/reward-certificate/$rewardId': typeof AuthenticatedRewardCertificateRewardIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/view-as/$userId': typeof AuthenticatedAdminViewAsUserIdRoute
  '/api/public/hooks/enqueue-payment-reminders': typeof ApiPublicHooksEnqueuePaymentRemindersRoute
  '/api/public/hooks/process-export-jobs': typeof ApiPublicHooksProcessExportJobsRoute
  '/api/public/hooks/process-payment-reminders': typeof ApiPublicHooksProcessPaymentRemindersRoute
  '/api/public/hooks/reconcile-payments': typeof ApiPublicHooksReconcilePaymentsRoute
  '/api/public/razorpay/webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/admin/draws/$drawId/pick': typeof ApiAdminDrawsDrawIdPickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/customer': typeof AuthenticatedCustomerRouteRouteWithChildren
  '/_authenticated/promoter': typeof AuthenticatedPromoterRouteRouteWithChildren
  '/_authenticated/commission-statement': typeof AuthenticatedCommissionStatementRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/kyc': typeof AuthenticatedKycRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/admin/$': typeof AuthenticatedAdminSplatRoute
  '/_authenticated/admin/approvals': typeof AuthenticatedAdminApprovalsRoute
  '/_authenticated/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/_authenticated/admin/commissions': typeof AuthenticatedAdminCommissionsRoute
  '/_authenticated/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/_authenticated/admin/draw-results': typeof AuthenticatedAdminDrawResultsRoute
  '/_authenticated/admin/email-preview': typeof AuthenticatedAdminEmailPreviewRoute
  '/_authenticated/admin/exports': typeof AuthenticatedAdminExportsRoute
  '/_authenticated/admin/gifts': typeof AuthenticatedAdminGiftsRoute
  '/_authenticated/admin/incentives': typeof AuthenticatedAdminIncentivesRoute
  '/_authenticated/admin/kyc-emails': typeof AuthenticatedAdminKycEmailsRoute
  '/_authenticated/admin/lucky-draw': typeof AuthenticatedAdminLuckyDrawRoute
  '/_authenticated/admin/membership-emails': typeof AuthenticatedAdminMembershipEmailsRoute
  '/_authenticated/admin/memberships': typeof AuthenticatedAdminMembershipsRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/plan-deletions': typeof AuthenticatedAdminPlanDeletionsRoute
  '/_authenticated/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/_authenticated/admin/promoters': typeof AuthenticatedAdminPromotersRoute
  '/_authenticated/admin/ranks': typeof AuthenticatedAdminRanksRoute
  '/_authenticated/admin/receipts': typeof AuthenticatedAdminReceiptsRoute
  '/_authenticated/admin/referral-tree': typeof AuthenticatedAdminReferralTreeRoute
  '/_authenticated/admin/reminder-jobs': typeof AuthenticatedAdminReminderJobsRoute
  '/_authenticated/admin/reminder-templates': typeof AuthenticatedAdminReminderTemplatesRoute
  '/_authenticated/admin/reminders': typeof AuthenticatedAdminRemindersRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/rewards': typeof AuthenticatedAdminRewardsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/site-settings': typeof AuthenticatedAdminSiteSettingsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/customer/draw-results': typeof AuthenticatedCustomerDrawResultsRoute
  '/_authenticated/customer/enroll': typeof AuthenticatedCustomerEnrollRoute
  '/_authenticated/customer/installments': typeof AuthenticatedCustomerInstallmentsRoute
  '/_authenticated/customer/lucky-draw': typeof AuthenticatedCustomerLuckyDrawRoute
  '/_authenticated/customer/membership': typeof AuthenticatedCustomerMembershipRoute
  '/_authenticated/customer/payments': typeof AuthenticatedCustomerPaymentsRoute
  '/_authenticated/customer/receipts': typeof AuthenticatedCustomerReceiptsRoute
  '/_authenticated/customer/referrals': typeof AuthenticatedCustomerReferralsRoute
  '/_authenticated/customer/rewards': typeof AuthenticatedCustomerRewardsRoute
  '/_authenticated/promoter/collections': typeof AuthenticatedPromoterCollectionsRoute
  '/_authenticated/promoter/commissions': typeof AuthenticatedPromoterCommissionsRoute
  '/_authenticated/promoter/customers': typeof AuthenticatedPromoterCustomersRoute
  '/_authenticated/promoter/lucky-draw': typeof AuthenticatedPromoterLuckyDrawRoute
  '/_authenticated/promoter/portfolio': typeof AuthenticatedPromoterPortfolioRoute
  '/_authenticated/promoter/rank': typeof AuthenticatedPromoterRankRoute
  '/_authenticated/receipts/$receiptNumber': typeof AuthenticatedReceiptsReceiptNumberRoute
  '/_authenticated/reward-certificate/$rewardId': typeof AuthenticatedRewardCertificateRewardIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/view-as/$userId': typeof AuthenticatedAdminViewAsUserIdRoute
  '/api/public/hooks/enqueue-payment-reminders': typeof ApiPublicHooksEnqueuePaymentRemindersRoute
  '/api/public/hooks/process-export-jobs': typeof ApiPublicHooksProcessExportJobsRoute
  '/api/public/hooks/process-payment-reminders': typeof ApiPublicHooksProcessPaymentRemindersRoute
  '/api/public/hooks/reconcile-payments': typeof ApiPublicHooksReconcilePaymentsRoute
  '/api/public/razorpay/webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/admin/draws/$drawId/pick': typeof ApiAdminDrawsDrawIdPickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/customer'
    | '/promoter'
    | '/commission-statement'
    | '/dashboard'
    | '/kyc'
    | '/settings'
    | '/admin/$'
    | '/admin/approvals'
    | '/admin/audit-log'
    | '/admin/commissions'
    | '/admin/customers'
    | '/admin/draw-results'
    | '/admin/email-preview'
    | '/admin/exports'
    | '/admin/gifts'
    | '/admin/incentives'
    | '/admin/kyc-emails'
    | '/admin/lucky-draw'
    | '/admin/membership-emails'
    | '/admin/memberships'
    | '/admin/payments'
    | '/admin/plan-deletions'
    | '/admin/plans'
    | '/admin/promoters'
    | '/admin/ranks'
    | '/admin/receipts'
    | '/admin/referral-tree'
    | '/admin/reminder-jobs'
    | '/admin/reminder-templates'
    | '/admin/reminders'
    | '/admin/reports'
    | '/admin/rewards'
    | '/admin/settings'
    | '/admin/site-settings'
    | '/admin/users'
    | '/customer/draw-results'
    | '/customer/enroll'
    | '/customer/installments'
    | '/customer/lucky-draw'
    | '/customer/membership'
    | '/customer/payments'
    | '/customer/receipts'
    | '/customer/referrals'
    | '/customer/rewards'
    | '/promoter/collections'
    | '/promoter/commissions'
    | '/promoter/customers'
    | '/promoter/lucky-draw'
    | '/promoter/portfolio'
    | '/promoter/rank'
    | '/receipts/$receiptNumber'
    | '/reward-certificate/$rewardId'
    | '/admin/'
    | '/admin/view-as/$userId'
    | '/api/public/hooks/enqueue-payment-reminders'
    | '/api/public/hooks/process-export-jobs'
    | '/api/public/hooks/process-payment-reminders'
    | '/api/public/hooks/reconcile-payments'
    | '/api/public/razorpay/webhook'
    | '/api/admin/draws/$drawId/pick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/customer'
    | '/promoter'
    | '/commission-statement'
    | '/dashboard'
    | '/kyc'
    | '/settings'
    | '/admin/$'
    | '/admin/approvals'
    | '/admin/audit-log'
    | '/admin/commissions'
    | '/admin/customers'
    | '/admin/draw-results'
    | '/admin/email-preview'
    | '/admin/exports'
    | '/admin/gifts'
    | '/admin/incentives'
    | '/admin/kyc-emails'
    | '/admin/lucky-draw'
    | '/admin/membership-emails'
    | '/admin/memberships'
    | '/admin/payments'
    | '/admin/plan-deletions'
    | '/admin/plans'
    | '/admin/promoters'
    | '/admin/ranks'
    | '/admin/receipts'
    | '/admin/referral-tree'
    | '/admin/reminder-jobs'
    | '/admin/reminder-templates'
    | '/admin/reminders'
    | '/admin/reports'
    | '/admin/rewards'
    | '/admin/settings'
    | '/admin/site-settings'
    | '/admin/users'
    | '/customer/draw-results'
    | '/customer/enroll'
    | '/customer/installments'
    | '/customer/lucky-draw'
    | '/customer/membership'
    | '/customer/payments'
    | '/customer/receipts'
    | '/customer/referrals'
    | '/customer/rewards'
    | '/promoter/collections'
    | '/promoter/commissions'
    | '/promoter/customers'
    | '/promoter/lucky-draw'
    | '/promoter/portfolio'
    | '/promoter/rank'
    | '/receipts/$receiptNumber'
    | '/reward-certificate/$rewardId'
    | '/admin'
    | '/admin/view-as/$userId'
    | '/api/public/hooks/enqueue-payment-reminders'
    | '/api/public/hooks/process-export-jobs'
    | '/api/public/hooks/process-payment-reminders'
    | '/api/public/hooks/reconcile-payments'
    | '/api/public/razorpay/webhook'
    | '/api/admin/draws/$drawId/pick'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/customer'
    | '/_authenticated/promoter'
    | '/_authenticated/commission-statement'
    | '/_authenticated/dashboard'
    | '/_authenticated/kyc'
    | '/_authenticated/settings'
    | '/_authenticated/admin/$'
    | '/_authenticated/admin/approvals'
    | '/_authenticated/admin/audit-log'
    | '/_authenticated/admin/commissions'
    | '/_authenticated/admin/customers'
    | '/_authenticated/admin/draw-results'
    | '/_authenticated/admin/email-preview'
    | '/_authenticated/admin/exports'
    | '/_authenticated/admin/gifts'
    | '/_authenticated/admin/incentives'
    | '/_authenticated/admin/kyc-emails'
    | '/_authenticated/admin/lucky-draw'
    | '/_authenticated/admin/membership-emails'
    | '/_authenticated/admin/memberships'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/plan-deletions'
    | '/_authenticated/admin/plans'
    | '/_authenticated/admin/promoters'
    | '/_authenticated/admin/ranks'
    | '/_authenticated/admin/receipts'
    | '/_authenticated/admin/referral-tree'
    | '/_authenticated/admin/reminder-jobs'
    | '/_authenticated/admin/reminder-templates'
    | '/_authenticated/admin/reminders'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/rewards'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/site-settings'
    | '/_authenticated/admin/users'
    | '/_authenticated/customer/draw-results'
    | '/_authenticated/customer/enroll'
    | '/_authenticated/customer/installments'
    | '/_authenticated/customer/lucky-draw'
    | '/_authenticated/customer/membership'
    | '/_authenticated/customer/payments'
    | '/_authenticated/customer/receipts'
    | '/_authenticated/customer/referrals'
    | '/_authenticated/customer/rewards'
    | '/_authenticated/promoter/collections'
    | '/_authenticated/promoter/commissions'
    | '/_authenticated/promoter/customers'
    | '/_authenticated/promoter/lucky-draw'
    | '/_authenticated/promoter/portfolio'
    | '/_authenticated/promoter/rank'
    | '/_authenticated/receipts/$receiptNumber'
    | '/_authenticated/reward-certificate/$rewardId'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/view-as/$userId'
    | '/api/public/hooks/enqueue-payment-reminders'
    | '/api/public/hooks/process-export-jobs'
    | '/api/public/hooks/process-payment-reminders'
    | '/api/public/hooks/reconcile-payments'
    | '/api/public/razorpay/webhook'
    | '/api/admin/draws/$drawId/pick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicHooksEnqueuePaymentRemindersRoute: typeof ApiPublicHooksEnqueuePaymentRemindersRoute
  ApiPublicHooksProcessExportJobsRoute: typeof ApiPublicHooksProcessExportJobsRoute
  ApiPublicHooksProcessPaymentRemindersRoute: typeof ApiPublicHooksProcessPaymentRemindersRoute
  ApiPublicHooksReconcilePaymentsRoute: typeof ApiPublicHooksReconcilePaymentsRoute
  ApiPublicRazorpayWebhookRoute: typeof ApiPublicRazorpayWebhookRoute
  ApiAdminDrawsDrawIdPickRoute: typeof ApiAdminDrawsDrawIdPickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kyc': {
      id: '/_authenticated/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof AuthenticatedKycRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commission-statement': {
      id: '/_authenticated/commission-statement'
      path: '/commission-statement'
      fullPath: '/commission-statement'
      preLoaderRoute: typeof AuthenticatedCommissionStatementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/promoter': {
      id: '/_authenticated/promoter'
      path: '/promoter'
      fullPath: '/promoter'
      preLoaderRoute: typeof AuthenticatedPromoterRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customer': {
      id: '/_authenticated/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof AuthenticatedCustomerRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/reward-certificate/$rewardId': {
      id: '/_authenticated/reward-certificate/$rewardId'
      path: '/reward-certificate/$rewardId'
      fullPath: '/reward-certificate/$rewardId'
      preLoaderRoute: typeof AuthenticatedRewardCertificateRewardIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/receipts/$receiptNumber': {
      id: '/_authenticated/receipts/$receiptNumber'
      path: '/receipts/$receiptNumber'
      fullPath: '/receipts/$receiptNumber'
      preLoaderRoute: typeof AuthenticatedReceiptsReceiptNumberRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/promoter/rank': {
      id: '/_authenticated/promoter/rank'
      path: '/rank'
      fullPath: '/promoter/rank'
      preLoaderRoute: typeof AuthenticatedPromoterRankRouteImport
      parentRoute: typeof AuthenticatedPromoterRouteRoute
    }
    '/_authenticated/promoter/portfolio': {
      id: '/_authenticated/promoter/portfolio'
      path: '/portfolio'
      fullPath: '/promoter/portfolio'
      preLoaderRoute: typeof AuthenticatedPromoterPortfolioRouteImport
      parentRoute: typeof AuthenticatedPromoterRouteRoute
    }
    '/_authenticated/promoter/lucky-draw': {
      id: '/_authenticated/promoter/lucky-draw'
      path: '/lucky-draw'
      fullPath: '/promoter/lucky-draw'
      preLoaderRoute: typeof AuthenticatedPromoterLuckyDrawRouteImport
      parentRoute: typeof AuthenticatedPromoterRouteRoute
    }
    '/_authenticated/promoter/customers': {
      id: '/_authenticated/promoter/customers'
      path: '/customers'
      fullPath: '/promoter/customers'
      preLoaderRoute: typeof AuthenticatedPromoterCustomersRouteImport
      parentRoute: typeof AuthenticatedPromoterRouteRoute
    }
    '/_authenticated/promoter/commissions': {
      id: '/_authenticated/promoter/commissions'
      path: '/commissions'
      fullPath: '/promoter/commissions'
      preLoaderRoute: typeof AuthenticatedPromoterCommissionsRouteImport
      parentRoute: typeof AuthenticatedPromoterRouteRoute
    }
    '/_authenticated/promoter/collections': {
      id: '/_authenticated/promoter/collections'
      path: '/collections'
      fullPath: '/promoter/collections'
      preLoaderRoute: typeof AuthenticatedPromoterCollectionsRouteImport
      parentRoute: typeof AuthenticatedPromoterRouteRoute
    }
    '/_authenticated/customer/rewards': {
      id: '/_authenticated/customer/rewards'
      path: '/rewards'
      fullPath: '/customer/rewards'
      preLoaderRoute: typeof AuthenticatedCustomerRewardsRouteImport
      parentRoute: typeof AuthenticatedCustomerRouteRoute
    }
    '/_authenticated/customer/referrals': {
      id: '/_authenticated/customer/referrals'
      path: '/referrals'
      fullPath: '/customer/referrals'
      preLoaderRoute: typeof AuthenticatedCustomerReferralsRouteImport
      parentRoute: typeof AuthenticatedCustomerRouteRoute
    }
    '/_authenticated/customer/receipts': {
      id: '/_authenticated/customer/receipts'
      path: '/receipts'
      fullPath: '/customer/receipts'
      preLoaderRoute: typeof AuthenticatedCustomerReceiptsRouteImport
      parentRoute: typeof AuthenticatedCustomerRouteRoute
    }
    '/_authenticated/customer/payments': {
      id: '/_authenticated/customer/payments'
      path: '/payments'
      fullPath: '/customer/payments'
      preLoaderRoute: typeof AuthenticatedCustomerPaymentsRouteImport
      parentRoute: typeof AuthenticatedCustomerRouteRoute
    }
    '/_authenticated/customer/membership': {
      id: '/_authenticated/customer/membership'
      path: '/membership'
      fullPath: '/customer/membership'
      preLoaderRoute: typeof AuthenticatedCustomerMembershipRouteImport
      parentRoute: typeof AuthenticatedCustomerRouteRoute
    }
    '/_authenticated/customer/lucky-draw': {
      id: '/_authenticated/customer/lucky-draw'
      path: '/lucky-draw'
      fullPath: '/customer/lucky-draw'
      preLoaderRoute: typeof AuthenticatedCustomerLuckyDrawRouteImport
      parentRoute: typeof AuthenticatedCustomerRouteRoute
    }
    '/_authenticated/customer/installments': {
      id: '/_authenticated/customer/installments'
      path: '/installments'
      fullPath: '/customer/installments'
      preLoaderRoute: typeof AuthenticatedCustomerInstallmentsRouteImport
      parentRoute: typeof AuthenticatedCustomerRouteRoute
    }
    '/_authenticated/customer/enroll': {
      id: '/_authenticated/customer/enroll'
      path: '/enroll'
      fullPath: '/customer/enroll'
      preLoaderRoute: typeof AuthenticatedCustomerEnrollRouteImport
      parentRoute: typeof AuthenticatedCustomerRouteRoute
    }
    '/_authenticated/customer/draw-results': {
      id: '/_authenticated/customer/draw-results'
      path: '/draw-results'
      fullPath: '/customer/draw-results'
      preLoaderRoute: typeof AuthenticatedCustomerDrawResultsRouteImport
      parentRoute: typeof AuthenticatedCustomerRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/site-settings': {
      id: '/_authenticated/admin/site-settings'
      path: '/site-settings'
      fullPath: '/admin/site-settings'
      preLoaderRoute: typeof AuthenticatedAdminSiteSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/rewards': {
      id: '/_authenticated/admin/rewards'
      path: '/rewards'
      fullPath: '/admin/rewards'
      preLoaderRoute: typeof AuthenticatedAdminRewardsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reminders': {
      id: '/_authenticated/admin/reminders'
      path: '/reminders'
      fullPath: '/admin/reminders'
      preLoaderRoute: typeof AuthenticatedAdminRemindersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reminder-templates': {
      id: '/_authenticated/admin/reminder-templates'
      path: '/reminder-templates'
      fullPath: '/admin/reminder-templates'
      preLoaderRoute: typeof AuthenticatedAdminReminderTemplatesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reminder-jobs': {
      id: '/_authenticated/admin/reminder-jobs'
      path: '/reminder-jobs'
      fullPath: '/admin/reminder-jobs'
      preLoaderRoute: typeof AuthenticatedAdminReminderJobsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/referral-tree': {
      id: '/_authenticated/admin/referral-tree'
      path: '/referral-tree'
      fullPath: '/admin/referral-tree'
      preLoaderRoute: typeof AuthenticatedAdminReferralTreeRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/receipts': {
      id: '/_authenticated/admin/receipts'
      path: '/receipts'
      fullPath: '/admin/receipts'
      preLoaderRoute: typeof AuthenticatedAdminReceiptsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/ranks': {
      id: '/_authenticated/admin/ranks'
      path: '/ranks'
      fullPath: '/admin/ranks'
      preLoaderRoute: typeof AuthenticatedAdminRanksRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/promoters': {
      id: '/_authenticated/admin/promoters'
      path: '/promoters'
      fullPath: '/admin/promoters'
      preLoaderRoute: typeof AuthenticatedAdminPromotersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/plans': {
      id: '/_authenticated/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AuthenticatedAdminPlansRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/plan-deletions': {
      id: '/_authenticated/admin/plan-deletions'
      path: '/plan-deletions'
      fullPath: '/admin/plan-deletions'
      preLoaderRoute: typeof AuthenticatedAdminPlanDeletionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/memberships': {
      id: '/_authenticated/admin/memberships'
      path: '/memberships'
      fullPath: '/admin/memberships'
      preLoaderRoute: typeof AuthenticatedAdminMembershipsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/membership-emails': {
      id: '/_authenticated/admin/membership-emails'
      path: '/membership-emails'
      fullPath: '/admin/membership-emails'
      preLoaderRoute: typeof AuthenticatedAdminMembershipEmailsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/lucky-draw': {
      id: '/_authenticated/admin/lucky-draw'
      path: '/lucky-draw'
      fullPath: '/admin/lucky-draw'
      preLoaderRoute: typeof AuthenticatedAdminLuckyDrawRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/kyc-emails': {
      id: '/_authenticated/admin/kyc-emails'
      path: '/kyc-emails'
      fullPath: '/admin/kyc-emails'
      preLoaderRoute: typeof AuthenticatedAdminKycEmailsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/incentives': {
      id: '/_authenticated/admin/incentives'
      path: '/incentives'
      fullPath: '/admin/incentives'
      preLoaderRoute: typeof AuthenticatedAdminIncentivesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/gifts': {
      id: '/_authenticated/admin/gifts'
      path: '/gifts'
      fullPath: '/admin/gifts'
      preLoaderRoute: typeof AuthenticatedAdminGiftsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/exports': {
      id: '/_authenticated/admin/exports'
      path: '/exports'
      fullPath: '/admin/exports'
      preLoaderRoute: typeof AuthenticatedAdminExportsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/email-preview': {
      id: '/_authenticated/admin/email-preview'
      path: '/email-preview'
      fullPath: '/admin/email-preview'
      preLoaderRoute: typeof AuthenticatedAdminEmailPreviewRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/draw-results': {
      id: '/_authenticated/admin/draw-results'
      path: '/draw-results'
      fullPath: '/admin/draw-results'
      preLoaderRoute: typeof AuthenticatedAdminDrawResultsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/customers': {
      id: '/_authenticated/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/commissions': {
      id: '/_authenticated/admin/commissions'
      path: '/commissions'
      fullPath: '/admin/commissions'
      preLoaderRoute: typeof AuthenticatedAdminCommissionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/audit-log': {
      id: '/_authenticated/admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AuthenticatedAdminAuditLogRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/approvals': {
      id: '/_authenticated/admin/approvals'
      path: '/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AuthenticatedAdminApprovalsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/$': {
      id: '/_authenticated/admin/$'
      path: '/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AuthenticatedAdminSplatRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/razorpay/webhook': {
      id: '/api/public/razorpay/webhook'
      path: '/api/public/razorpay/webhook'
      fullPath: '/api/public/razorpay/webhook'
      preLoaderRoute: typeof ApiPublicRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/reconcile-payments': {
      id: '/api/public/hooks/reconcile-payments'
      path: '/api/public/hooks/reconcile-payments'
      fullPath: '/api/public/hooks/reconcile-payments'
      preLoaderRoute: typeof ApiPublicHooksReconcilePaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-payment-reminders': {
      id: '/api/public/hooks/process-payment-reminders'
      path: '/api/public/hooks/process-payment-reminders'
      fullPath: '/api/public/hooks/process-payment-reminders'
      preLoaderRoute: typeof ApiPublicHooksProcessPaymentRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-export-jobs': {
      id: '/api/public/hooks/process-export-jobs'
      path: '/api/public/hooks/process-export-jobs'
      fullPath: '/api/public/hooks/process-export-jobs'
      preLoaderRoute: typeof ApiPublicHooksProcessExportJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/enqueue-payment-reminders': {
      id: '/api/public/hooks/enqueue-payment-reminders'
      path: '/api/public/hooks/enqueue-payment-reminders'
      fullPath: '/api/public/hooks/enqueue-payment-reminders'
      preLoaderRoute: typeof ApiPublicHooksEnqueuePaymentRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/view-as/$userId': {
      id: '/_authenticated/admin/view-as/$userId'
      path: '/view-as/$userId'
      fullPath: '/admin/view-as/$userId'
      preLoaderRoute: typeof AuthenticatedAdminViewAsUserIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/admin/draws/$drawId/pick': {
      id: '/api/admin/draws/$drawId/pick'
      path: '/api/admin/draws/$drawId/pick'
      fullPath: '/api/admin/draws/$drawId/pick'
      preLoaderRoute: typeof ApiAdminDrawsDrawIdPickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminSplatRoute: typeof AuthenticatedAdminSplatRoute
  AuthenticatedAdminApprovalsRoute: typeof AuthenticatedAdminApprovalsRoute
  AuthenticatedAdminAuditLogRoute: typeof AuthenticatedAdminAuditLogRoute
  AuthenticatedAdminCommissionsRoute: typeof AuthenticatedAdminCommissionsRoute
  AuthenticatedAdminCustomersRoute: typeof AuthenticatedAdminCustomersRoute
  AuthenticatedAdminDrawResultsRoute: typeof AuthenticatedAdminDrawResultsRoute
  AuthenticatedAdminEmailPreviewRoute: typeof AuthenticatedAdminEmailPreviewRoute
  AuthenticatedAdminExportsRoute: typeof AuthenticatedAdminExportsRoute
  AuthenticatedAdminGiftsRoute: typeof AuthenticatedAdminGiftsRoute
  AuthenticatedAdminIncentivesRoute: typeof AuthenticatedAdminIncentivesRoute
  AuthenticatedAdminKycEmailsRoute: typeof AuthenticatedAdminKycEmailsRoute
  AuthenticatedAdminLuckyDrawRoute: typeof AuthenticatedAdminLuckyDrawRoute
  AuthenticatedAdminMembershipEmailsRoute: typeof AuthenticatedAdminMembershipEmailsRoute
  AuthenticatedAdminMembershipsRoute: typeof AuthenticatedAdminMembershipsRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminPlanDeletionsRoute: typeof AuthenticatedAdminPlanDeletionsRoute
  AuthenticatedAdminPlansRoute: typeof AuthenticatedAdminPlansRoute
  AuthenticatedAdminPromotersRoute: typeof AuthenticatedAdminPromotersRoute
  AuthenticatedAdminRanksRoute: typeof AuthenticatedAdminRanksRoute
  AuthenticatedAdminReceiptsRoute: typeof AuthenticatedAdminReceiptsRoute
  AuthenticatedAdminReferralTreeRoute: typeof AuthenticatedAdminReferralTreeRoute
  AuthenticatedAdminReminderJobsRoute: typeof AuthenticatedAdminReminderJobsRoute
  AuthenticatedAdminReminderTemplatesRoute: typeof AuthenticatedAdminReminderTemplatesRoute
  AuthenticatedAdminRemindersRoute: typeof AuthenticatedAdminRemindersRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminRewardsRoute: typeof AuthenticatedAdminRewardsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSiteSettingsRoute: typeof AuthenticatedAdminSiteSettingsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminViewAsUserIdRoute: typeof AuthenticatedAdminViewAsUserIdRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminSplatRoute: AuthenticatedAdminSplatRoute,
    AuthenticatedAdminApprovalsRoute: AuthenticatedAdminApprovalsRoute,
    AuthenticatedAdminAuditLogRoute: AuthenticatedAdminAuditLogRoute,
    AuthenticatedAdminCommissionsRoute: AuthenticatedAdminCommissionsRoute,
    AuthenticatedAdminCustomersRoute: AuthenticatedAdminCustomersRoute,
    AuthenticatedAdminDrawResultsRoute: AuthenticatedAdminDrawResultsRoute,
    AuthenticatedAdminEmailPreviewRoute: AuthenticatedAdminEmailPreviewRoute,
    AuthenticatedAdminExportsRoute: AuthenticatedAdminExportsRoute,
    AuthenticatedAdminGiftsRoute: AuthenticatedAdminGiftsRoute,
    AuthenticatedAdminIncentivesRoute: AuthenticatedAdminIncentivesRoute,
    AuthenticatedAdminKycEmailsRoute: AuthenticatedAdminKycEmailsRoute,
    AuthenticatedAdminLuckyDrawRoute: AuthenticatedAdminLuckyDrawRoute,
    AuthenticatedAdminMembershipEmailsRoute:
      AuthenticatedAdminMembershipEmailsRoute,
    AuthenticatedAdminMembershipsRoute: AuthenticatedAdminMembershipsRoute,
    AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
    AuthenticatedAdminPlanDeletionsRoute: AuthenticatedAdminPlanDeletionsRoute,
    AuthenticatedAdminPlansRoute: AuthenticatedAdminPlansRoute,
    AuthenticatedAdminPromotersRoute: AuthenticatedAdminPromotersRoute,
    AuthenticatedAdminRanksRoute: AuthenticatedAdminRanksRoute,
    AuthenticatedAdminReceiptsRoute: AuthenticatedAdminReceiptsRoute,
    AuthenticatedAdminReferralTreeRoute: AuthenticatedAdminReferralTreeRoute,
    AuthenticatedAdminReminderJobsRoute: AuthenticatedAdminReminderJobsRoute,
    AuthenticatedAdminReminderTemplatesRoute:
      AuthenticatedAdminReminderTemplatesRoute,
    AuthenticatedAdminRemindersRoute: AuthenticatedAdminRemindersRoute,
    AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
    AuthenticatedAdminRewardsRoute: AuthenticatedAdminRewardsRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminSiteSettingsRoute: AuthenticatedAdminSiteSettingsRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminViewAsUserIdRoute: AuthenticatedAdminViewAsUserIdRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedCustomerRouteRouteChildren {
  AuthenticatedCustomerDrawResultsRoute: typeof AuthenticatedCustomerDrawResultsRoute
  AuthenticatedCustomerEnrollRoute: typeof AuthenticatedCustomerEnrollRoute
  AuthenticatedCustomerInstallmentsRoute: typeof AuthenticatedCustomerInstallmentsRoute
  AuthenticatedCustomerLuckyDrawRoute: typeof AuthenticatedCustomerLuckyDrawRoute
  AuthenticatedCustomerMembershipRoute: typeof AuthenticatedCustomerMembershipRoute
  AuthenticatedCustomerPaymentsRoute: typeof AuthenticatedCustomerPaymentsRoute
  AuthenticatedCustomerReceiptsRoute: typeof AuthenticatedCustomerReceiptsRoute
  AuthenticatedCustomerReferralsRoute: typeof AuthenticatedCustomerReferralsRoute
  AuthenticatedCustomerRewardsRoute: typeof AuthenticatedCustomerRewardsRoute
}

const AuthenticatedCustomerRouteRouteChildren: AuthenticatedCustomerRouteRouteChildren =
  {
    AuthenticatedCustomerDrawResultsRoute:
      AuthenticatedCustomerDrawResultsRoute,
    AuthenticatedCustomerEnrollRoute: AuthenticatedCustomerEnrollRoute,
    AuthenticatedCustomerInstallmentsRoute:
      AuthenticatedCustomerInstallmentsRoute,
    AuthenticatedCustomerLuckyDrawRoute: AuthenticatedCustomerLuckyDrawRoute,
    AuthenticatedCustomerMembershipRoute: AuthenticatedCustomerMembershipRoute,
    AuthenticatedCustomerPaymentsRoute: AuthenticatedCustomerPaymentsRoute,
    AuthenticatedCustomerReceiptsRoute: AuthenticatedCustomerReceiptsRoute,
    AuthenticatedCustomerReferralsRoute: AuthenticatedCustomerReferralsRoute,
    AuthenticatedCustomerRewardsRoute: AuthenticatedCustomerRewardsRoute,
  }

const AuthenticatedCustomerRouteRouteWithChildren =
  AuthenticatedCustomerRouteRoute._addFileChildren(
    AuthenticatedCustomerRouteRouteChildren,
  )

interface AuthenticatedPromoterRouteRouteChildren {
  AuthenticatedPromoterCollectionsRoute: typeof AuthenticatedPromoterCollectionsRoute
  AuthenticatedPromoterCommissionsRoute: typeof AuthenticatedPromoterCommissionsRoute
  AuthenticatedPromoterCustomersRoute: typeof AuthenticatedPromoterCustomersRoute
  AuthenticatedPromoterLuckyDrawRoute: typeof AuthenticatedPromoterLuckyDrawRoute
  AuthenticatedPromoterPortfolioRoute: typeof AuthenticatedPromoterPortfolioRoute
  AuthenticatedPromoterRankRoute: typeof AuthenticatedPromoterRankRoute
}

const AuthenticatedPromoterRouteRouteChildren: AuthenticatedPromoterRouteRouteChildren =
  {
    AuthenticatedPromoterCollectionsRoute:
      AuthenticatedPromoterCollectionsRoute,
    AuthenticatedPromoterCommissionsRoute:
      AuthenticatedPromoterCommissionsRoute,
    AuthenticatedPromoterCustomersRoute: AuthenticatedPromoterCustomersRoute,
    AuthenticatedPromoterLuckyDrawRoute: AuthenticatedPromoterLuckyDrawRoute,
    AuthenticatedPromoterPortfolioRoute: AuthenticatedPromoterPortfolioRoute,
    AuthenticatedPromoterRankRoute: AuthenticatedPromoterRankRoute,
  }

const AuthenticatedPromoterRouteRouteWithChildren =
  AuthenticatedPromoterRouteRoute._addFileChildren(
    AuthenticatedPromoterRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedCustomerRouteRoute: typeof AuthenticatedCustomerRouteRouteWithChildren
  AuthenticatedPromoterRouteRoute: typeof AuthenticatedPromoterRouteRouteWithChildren
  AuthenticatedCommissionStatementRoute: typeof AuthenticatedCommissionStatementRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedKycRoute: typeof AuthenticatedKycRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedReceiptsReceiptNumberRoute: typeof AuthenticatedReceiptsReceiptNumberRoute
  AuthenticatedRewardCertificateRewardIdRoute: typeof AuthenticatedRewardCertificateRewardIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedCustomerRouteRoute: AuthenticatedCustomerRouteRouteWithChildren,
  AuthenticatedPromoterRouteRoute: AuthenticatedPromoterRouteRouteWithChildren,
  AuthenticatedCommissionStatementRoute: AuthenticatedCommissionStatementRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedKycRoute: AuthenticatedKycRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedReceiptsReceiptNumberRoute:
    AuthenticatedReceiptsReceiptNumberRoute,
  AuthenticatedRewardCertificateRewardIdRoute:
    AuthenticatedRewardCertificateRewardIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicHooksEnqueuePaymentRemindersRoute:
    ApiPublicHooksEnqueuePaymentRemindersRoute,
  ApiPublicHooksProcessExportJobsRoute: ApiPublicHooksProcessExportJobsRoute,
  ApiPublicHooksProcessPaymentRemindersRoute:
    ApiPublicHooksProcessPaymentRemindersRoute,
  ApiPublicHooksReconcilePaymentsRoute: ApiPublicHooksReconcilePaymentsRoute,
  ApiPublicRazorpayWebhookRoute: ApiPublicRazorpayWebhookRoute,
  ApiAdminDrawsDrawIdPickRoute: ApiAdminDrawsDrawIdPickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
